build:
  environment:
    php:
      version: 7.3
      pecl_extensions:
        - mongodb
    memcached: true

  nodes:
    my-node:
      services:
        # For available tags, see https://hub.docker.com/_/mongo/
        mongo: 4
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run
          - command: 'vendor/bin/phpunit --dump-xdebug-filter xdebug-filter.php'
checks:

  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true

    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true

    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      other:
        after_type_cast: false
