build:
  environment:
    php:
      version: 7.2
      pecl_extensions:
        - memcached
        - mongodb
    memcached: true

  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run
          - command: 'vendor/bin/phpunit --dump-xdebug-filter xdebug-filter.php'
          -
            command: 'vendor/bin/phpunit --prepend xdebug-filter.php --coverage-clover=some-file'
            coverage:
              file: 'some-file'
              format: 'clover'

filter:
  excluded_paths: [docs/*, resources/*, tests/*, database/*, config/*]

checks:

  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true

    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true

    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      other:
        after_type_cast: false
