name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: ['8.2', '8.3']
        os: ['ubuntu-latest']
        mongodb: ['3.6', '4.0', '4.2']
    services:
      mongo:
        image: mongo:${{ matrix.mongodb }}
        ports:
          - 27017:27017

    name: PHP v${{ matrix.php }} with Mongo v${{ matrix.mongodb }}
    steps:
    - uses: actions/checkout@v2
    - name: "Installing php"
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: curl,mbstring,xdebug
        coverage: xdebug
        tools: composer
    - name: Show PHP version
      run: php -v && composer -V
    - name: Download Composer cache dependencies from cache
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache Composer dependencies
      uses: actions/cache@v1
      with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.os }}-composer-
    - name: Install dependencies
      run: |
        composer install --no-interaction
    - name: Run tests
      run: |
        ./vendor/bin/phpunit --coverage-clover coverage.xml
      env:
        MONGO_HOST: 0.0.0.0
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
